### ISSUE TITLE
Any chance of an update for Slate 16.9/React 15.4?

### ISSUE THREAD

**Issue by Slapbox** [oozou/slate-wrapped-block-plugin#2]
This plugin looks great, but unfortunately it doesn't function with the latest version of Slate. Any chance of an update to this plugin, or is it basically a dead end as underlying pieces this relies on have changed?

Either way, great contribution!

**Comment by Slapbox** [comment]
I'd like to take a crack at solving this issue, but I can't yet find what specifically has changed that breaks this plugin. I know it happens when Slate hits version 13.

Here's the changes for Slate 13: https://github.com/ianstormtaylor/slate/releases?after=v0.13.9

Do you have any idea which change broke the plugin? I'm guessing keys, but I'm not sure and haven't been able to deduce yet.

Thanks for any help you can provide.

**Comment by aunsuwijak** [comment]
@Slapbox Yes, will update soon.

**Comment by caffeaun** [comment]
Done

**Comment by Nantris** [comment]
Wow that was so fast! I wasn't even sure whether to expect a response, let alone such a fast update. Thank you!

**Comment by Nantris** [comment]
I just tried the example and it definitely works! 

There's just one issue when compared with your previous version. The new version does not remove wrapped blocks after they have lost focus.

Thanks again for your great work and your amazingly fast response.

**Comment by caffeaun** [comment]
@Slapbox Your welcome.
